//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONJUNTO
    {
        public decimal CODCONJUNTO { get; set; }
        public decimal CODPRENDA { get; set; }
        public decimal CANTIDAD { get; set; }
    
        public virtual PRENDA PRENDA { get; set; }
        public virtual PRENDA PRENDA1 { get; set; }
    }
}
