//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public decimal CODEMPLEADO { get; set; }
        public string PUESTO { get; set; }
        public decimal SALARIO { get; set; }
        public decimal TELEFONO { get; set; }
        public string DIRECCION { get; set; }
    }
}
