//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENESPERA
    {
        public decimal CODORDENPRODUCCION { get; set; }
        public decimal CODMATERIALFALTANTE { get; set; }
        public decimal UNIDADMEDIDA { get; set; }
        public Nullable<decimal> CODORDENCOMPRA { get; set; }
        public decimal CANTIDADFALTANTE { get; set; }
    
        public virtual MATERIAPRIMA MATERIAPRIMA { get; set; }
        public virtual ORDENCOMPRA ORDENCOMPRA { get; set; }
        public virtual ORDENPRODUCCION ORDENPRODUCCION { get; set; }
        public virtual UNIDADMEDIDA UNIDADMEDIDA1 { get; set; }
    }
}
