//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDI2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ORDENCOMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDENCOMPRA()
        {
            this.LINEAORDENCOMPRA = new HashSet<LINEAORDENCOMPRA>();
            this.ORDENESPERA = new HashSet<ORDENESPERA>();
        }
    
        public decimal CODORDENCOMPRA { get; set; }
        public decimal CODPROVEEDOR { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime FECHAENTREGA { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime FECHAEMISION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINEAORDENCOMPRA> LINEAORDENCOMPRA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDENESPERA> ORDENESPERA { get; set; }
    }
}
