//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRENDA()
        {
            this.CONJUNTO = new HashSet<CONJUNTO>();
            this.CONJUNTO1 = new HashSet<CONJUNTO>();
            this.LINEAPEDIDO = new HashSet<LINEAPEDIDO>();
            this.MATERIALPRENDA = new HashSet<MATERIALPRENDA>();
            this.ORDENPRODUCCION = new HashSet<ORDENPRODUCCION>();
        }
    
        public decimal CODPRENDA { get; set; }
        public decimal PRECIO { get; set; }
        public decimal EXISTENCIAACTUAL { get; set; }
        public decimal CODESTILO { get; set; }
        public string TALLA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONJUNTO> CONJUNTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONJUNTO> CONJUNTO1 { get; set; }
        public virtual ESTILO ESTILO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINEAPEDIDO> LINEAPEDIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIALPRENDA> MATERIALPRENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDENPRODUCCION> ORDENPRODUCCION { get; set; }

        public string INFOPRENDA { get { return "Prenda " + this.CODPRENDA + " (Estilo " + this.CODESTILO + " " + this.TALLA + ")"; } }
    }

    public enum TALLAS { XXL, XL, L, M, S}
}
