//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDI2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.MATERIAPROVEEDOR = new HashSet<MATERIAPROVEEDOR>();
            this.ORDENCOMPRA = new HashSet<ORDENCOMPRA>();
        }
        public decimal CODPROVEEDOR { get; set; }
        public string NOMBRE { get; set; }
        public string TIPO { get; set; }
        public string DIRECCION { get; set; }
        public decimal TELEFONO { get; set; }
        public string NBRCONTACTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAPROVEEDOR> MATERIAPROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDENCOMPRA> ORDENCOMPRA { get; set; }
        public virtual PROVEEDOREXTRANGERO PROVEEDOREXTRANGERO { get; set; }
        public virtual PROVEEDORNACIONAL PROVEEDORNACIONAL { get; set; }
    }
}
