//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDADMEDIDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNIDADMEDIDA()
        {
            this.CONVERSIONUNIDADMEDIDA = new HashSet<CONVERSIONUNIDADMEDIDA>();
            this.CONVERSIONUNIDADMEDIDA1 = new HashSet<CONVERSIONUNIDADMEDIDA>();
            this.LINEAORDENCOMPRA = new HashSet<LINEAORDENCOMPRA>();
            this.MATERIALPRENDA = new HashSet<MATERIALPRENDA>();
            this.MATERIAPRIMA = new HashSet<MATERIAPRIMA>();
            this.ORDENESPERA = new HashSet<ORDENESPERA>();
        }
    
        public decimal CODUNIDADMEDIDA { get; set; }
        public string NBRMEDIDA { get; set; }
        public string DESCRIPCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONVERSIONUNIDADMEDIDA> CONVERSIONUNIDADMEDIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONVERSIONUNIDADMEDIDA> CONVERSIONUNIDADMEDIDA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINEAORDENCOMPRA> LINEAORDENCOMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIALPRENDA> MATERIALPRENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAPRIMA> MATERIAPRIMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDENESPERA> ORDENESPERA { get; set; }
    }
}
